#!/bin/sh

# 루트 디렉토리의 CHANGELOG.md 파일을 패키지 디렉토리로 복사
cp "$(pwd)/CHANGELOG.md" "$(pwd)/Assets/JJ4Unity/CHANGELOG.md"

# 변경 사항이 있는지 확인하고 스테이징
if [ -n "$(git status --porcelain)" ]; then
  git add Assets/JJ4Unity/CHANGELOG.md
fi
